---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "post.fullname" . }}
  labels:
    app: {{ .Values.app.name }}
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Values.app.name }}
        component: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: {{ .Chart.Name }}
          protocol: TCP
        env:
          - name: POST_DATABASE_HOST
            value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
          - name: POST_DATABASE
            value: post
