FROM ubuntu:16.04

LABEL maintainer="serboox@gmail.com" \
    version="1.0" \
    description="Homework №16"

ENV APP_HOME /app
ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

USER root

ADD . $APP_HOME
WORKDIR $APP_HOME
RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    ruby-full ruby-dev build-essential && \
    gem install bundler --no-ri --no-rdoc

CMD ["puma"]
