FROM ruby:2.2

LABEL maintainer="serboox@gmail.com" \
    version="1.0" \
    description="Homework №16"

ENV  APP_HOME /app
ENV  COMMENT_DATABASE_HOST comment_db
ENV  COMMENT_DATABASE comments

USER root

ADD . $APP_HOME
WORKDIR $APP_HOME

RUN cat apt/sources.jessie > /etc/apt/sources.list && \
    apt-get -o Acquire::Check-Valid-Until=false update && \
    #DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    #apt-utils apt-transport-https gnupg
    #apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 1394DEA3 && \
    #DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::Check-Valid-Until=false -y dist-upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::Check-Valid-Until=false -y --no-install-recommends install \
    # SYSTEM
    #sudo apt-transport-https ca-certificates \
    build-essential \
    # SHELL
    # bash bash-completion \
    # TOOLS
    # procps less vim wget curl make git
    && bundle install

CMD ["puma"]
