---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: {{ .Values.app.name }}
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Values.app.name }}
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
