version: '3.3'
services:
  prometheus:
    image: ${IMAGE_USER}/prometheus
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - ${CADVISOR_PORT}:${CADVISOR_PORT}
    networks:
      - front_net
  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    networks:
      - front_net
  alertmanager:
    image: ${IMAGE_USER}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - ${ALERTMANAGER_PORT}:${ALERTMANAGER_PORT}
    networks:
      - front_net
volumes:
  prometheus_data:
  grafana_data:

networks:
  front_net:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "false"
    ipam:
        driver: default
        config:
            - subnet: 10.0.1.0/24
