---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:
  type: NodePort
  ports:
  - port: 9292
    #nodePort: 30407
    protocol: TCP
    targetPort: 9292
    #name: local
  selector:
    app: reddit
    component: ui
